version: '2'
services:
  web:
    build: .
    container_name: "myapp"
    environment:
      - DOCKER=1
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - "27017:27017"